---
- hosts: 127.0.0.1
  connection: local
  become: true

  tasks: 
    - apt: name={{ item }}
      with_items:
        - awscli
        - nodejs
    - npm: name={{ item }} global=yes
      with_items:
        - n
        - serverless
        - eslint
        - eslint-config-google

    - command: n 6.10

    - apt_repository: repo=ppa:gophers/archive
    - apt: name=golang-1.9-go
    - file: path=/usr/bin/go src=/usr/lib/go-1.9/bin/go state=link

    - command: go get github.com/tools/godep
